Repository Teknodev/composer-tools, pull requests merged in 2024-12, with the labels that each got.

#396 Team15
  editor-components/team/team-15/team15.module.scss
  editor-components/team/team-15/team15.tsx
Labels: change-req

#380 Formmodal1
  editor-components/modal/formmodal1/formmodal1.module.scss
  editor-components/modal/formmodal1/formmodal1.tsx
Labels: code-looks-good

#381 Notification modal1
  editor-components/modal/notification-modal1/notificationmodal1.module.scss
  editor-components/modal/notification-modal1/notificationmodal1.tsx
Labels: code-looks-good

#377 List 2
  editor-components/list/list2/list2.module.scss
  editor-components/list/list2/list2.tsx
Labels: change-req

#225 header-27
  editor-components/header/header27/header27.module.scss
  editor-components/header/header27/header27.tsx
Labels: invalid

#389 feature2 standardization
  editor-components/feature/feature2/feature2.module.scss
  editor-components/feature/feature2/feature2.tsx
Labels: change-req

#393 Feature3 standardization
  editor-components/feature/feature3/feature3.module.scss
  editor-components/feature/feature3/feature3.tsx
Labels: change-req

#293 stats2
  editor-components/stats/stats2/stats2.module.scss
  editor-components/stats/stats2/stats2.tsx
Labels: invalid
