Repository Teknodev/composer-tools, pull requests merged in 2024-08, with the labels that each got.

#149 list3
  editor-components/list/list3/list3.module.scss
  editor-components/list/list3/list3.tsx
Labels: checked

#157 Header 10
  editor-components/header/header10/header10.module.scss
  editor-components/header/header10/header10.tsx
Labels: draft

#198 header-31
  editor-components/header/header31/header31.module.scss
  editor-components/header/header31/header31.tsx
Labels: invalid

#194 download1
  editor-components/download/download1/download1.module.scss
  editor-components/download/download1/download1.tsx
Labels: invalid

#201 list-1
  editor-components/list/list1/list1.module.scss
  editor-components/list/list1/list1.tsx
Labels: code-looks-good

#192 header 14
  editor-components/header/header14/header14.module.scss
  editor-components/header/header14/header14.tsx
Labels: checked

#165 Content8
  editor-components/content/content8/content8.module.scss
  editor-components/content/content8/content8.tsx
Labels: checked

#314 fix: update header9
  editor-components/header/header9/header9.module.scss
  editor-components/header/header9/header9.tsx
Labels: checked

#170 navbar 3 changes
  editor-components/navigators/navbar3/navbar3.module.scss
  editor-components/navigators/navbar3/navbar3.tsx
Labels: checked

#215 team14
  editor-components/team/team-14/team14.module.scss
  editor-components/team/team-14/team14.tsx
Labels: draft

#193 team8
  editor-components/team/team-8/team8.module.scss
  editor-components/team/team-8/team8.tsx
Labels: invalid

#233 form10
  editor-components/contacts/form10/form10.module.scss
  editor-components/contacts/form10/form10.tsx
Labels: draft

#221 pricing9
  editor-components/pricing-table/pricing-table9/pricing-table9.module.scss
  editor-components/pricing-table/pricing-table9/pricing-table9.tsx
Labels: draft

#240 Content4
  editor-components/content/content4/content4.module.scss
  editor-components/content/content4/content4.tsx
Labels: invalid

#241 download5
  editor-components/download/download5/appleicons.png
  editor-components/download/download5/download5.module.scss
  editor-components/download/download5/download5.tsx
  editor-components/download/download5/google-play.png
  editor-components/download/download5/phonescreen.png
  editor-components/download/download5/pngegg.png
Labels: invalid

#244 calltoaction5
  editor-components/EditorComponent.tsx
  editor-components/call_to_action/call_to_action5/call_to_action5.module.scss
  editor-components/call_to_action/call_to_action5/call_to_action5.tsx
Labels: invalid

#227 refactor: team-9 component
  editor-components/team/team-9/team9.module.scss
  editor-components/team/team-9/team9.tsx
Labels: checked

#248 header26
  editor-components/header/header26/header26.module.scss
  editor-components/header/header26/header26.tsx
Labels: checked

#256 download-7
  editor-components/download/download7/download7.module.scss
  editor-components/download/download7/download7.tsx
Labels: checked

#253 Download6
  editor-components/download/download6/download6.module.scss
  editor-components/download/download6/download6.tsx
Labels: checked

#232 form7
  editor-components/contacts/form7/form7.module.scss
  editor-components/contacts/form7/form7.tsx
Labels: checked

#254 feature6
  editor-components/feature/feature6/feature6.module.scss
  editor-components/feature/feature6/feature6.tsx
Labels: checked

#264 notificationalmodal2
  editor-components/modal/notificationmodal2/notificationmodal2.module.scss
  editor-components/modal/notificationmodal2/notificationmodal2.tsx
  editor-components/registerables.tsx
Labels: code-looks-good

#260 Appereance tweak
  editor-components/feature/feature12/feature12.module.scss
  editor-components/feature/feature12/feature12.tsx
Labels: code-needs-revisit

#259 stats5
  editor-components/stats/stats5/stats5.module.scss
  editor-components/stats/stats5/stats5.tsx
Labels: code-needs-revisit

#267 logoClouds3
  editor-components/logo-clouds/logo-comp3/logo-comp3.module.scss
  editor-components/logo-clouds/logo-comp3/logo-comp3.tsx
Labels: code-needs-revisit

#272 Content19
  editor-components/content/content19/content19.module.scss
  editor-components/content/content19/content19.tsx
Labels: code-needs-revisit

#271 Feature7
  editor-components/feature/feature7/feature7.module.scss
  editor-components/feature/feature7/feature7.tsx
Labels: code-looks-good

#174 Team 6
  editor-components/team/team-6/team6.module.scss
  editor-components/team/team-6/team6.tsx
Labels: draft
