Repository Teknodev/composer-tools, pull requests merged in 2024-07, with the labels that each got.

#246 feature3
  editor-components/feature/feature3/feature3.module.scss
  editor-components/feature/feature3/feature3.tsx
Labels: checked

#238 form-11
  editor-components/contacts/form11/form11.module.scss
  editor-components/contacts/form11/form11.tsx
Labels: checked

#239 callToAction8
  editor-components/call_to_action/call_to_action8/call_to_action8.module.scss
  editor-components/call_to_action/call_to_action8/call_to_action8.tsx
Labels: checked

#218 pricing 8
  editor-components/pricing-table/pricing-table8/pricing-table8.module.scss
  editor-components/pricing-table/pricing-table8/pricing-table8.tsx
Labels: draft

#302 feat: header5
  editor-components/header/header5/header5.module.scss
  editor-components/header/header5/header5.tsx
Labels: code-looks-good
